# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscriber.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("subscriber.proto", :syntax => :proto3) do
    add_message "subscriberinfo.Subscriber" do
      optional :subscriber_id, :int64, 1
      optional :name, :string, 2
      optional :status, :string, 3
    end
  end
end

module Subscriberinfo
  Subscriber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("subscriberinfo.Subscriber").msgclass
end
